# Ondrej Urbanek testing GitHub sync

phrase:
  access_token: 57511b30d757a7ac095ef4f67527ec49cc47bf140dbd897a8d75a14ea7acd6c7
  project_id: 3cc9fe7caf5f4e1e47e97b057d186c0f
  push:
    sources:
    - file: ./Strings/<locale_name>.json
      params:
        locale_id: 7e624e1cca92e873c61f2a97ea4405c2
        file_format: simple_json
  pull:
    targets:
    - file: ./Strings/<locale_name>.json
      params:
        file_format: simple_json
