phrase:
  access_token: d3f31c5732d55a42d3098d185800a6ede9d27e75debd27a563f715d5a1d98644
  project_id: 32b61ddb971dc55f15a10417384bb51f

  push:
    sources:
    - file: ./Baset/en.json
      params:
        file_format: simple_json
        locale_id: en #Can be the name (e.g. en-US) or public id (via Language settings -> API) of the locale. Preferred is the public id.
        update_translations: true #Indicates whether existing translations should be updated with the file content.
  pull:
    targets:
    - file: ./messages.json
      params:
        file_format: simple_json
        locale_id: en
        include_empty_translations: true
        tags: "142080"

    - file: ./melio.locale.json
      params:
        file_format: simple_json
        locale_id: en-melio
        include_empty_translations: true
        tags: "142080"

    - file: ./capOne.locale.json
      params:
        file_format: simple_json
        locale_id: en-capital-one
        include_empty_translations: true
        tags: "142080"

    - file: ./clover.locale.json
      params:
        file_format: simple_json
        locale_id: en-clover
        include_empty_translations: true
        tags: "142080"

    - file: ./sbb.locale.json
      params:
        file_format: simple_json
        locale_id: en-sbb
        include_empty_translations: true
        tags: "142080"

    - file: ./fiserv.locale.json
      params:
        file_format: simple_json
        locale_id: en-fiserv
        include_empty_translations: true
        tags: "142080"
