phrase:
  access_token: 57511b30d757a7ac095ef4f67527ec49cc47bf140dbd897a8d75a14ea7acd6c7
  project_id: 7921eb08f9ae126a17e3fa7dc95c7db3
  push:
    sources:
    - file: ./Phrase/PhraseSampleItems/languages/<locale_name>.json
      params:
        file_format: simple_json
        locale_id: ad646f68fd703662815565734ed51226
  pull:
    targets:
    - file: ./Phrase/PhraseSampleItems/languages/<locale_name>.json
      params:
        file_format: simple_json

